#!/bin/sh

export GDK_DPI_SCALE=0.75
export GDK_SCALE=1

xrdb -merge ~/.Xresources
xwallpaper --zoom ~/wall/wallpaper.jpg &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

############ Window Settings ####################

bspc config border_width         1
bspc config window_gap           5
bspc config focus_follows_pointer true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config top_padding          52

bspc config focused_border_color "#131a1c"
bspc config normal_border_color  "#131a1c"

######### Program Rules ################
bspc rule -a KotatogramDesktop desktop='^4'
bspc rule -a Firefox            desktop='^1'
bspc rule -a Zathura            state=tiled
bspc rule -a TelegramDesktop    desktop='^4'

######### Autostart ################
dunst &
xsetroot -cursor_name left_ptr &
xsetroot -xcf /usr/share/icons/Adwaita/cursors/left_ptr 24 &
picom --config ~/.config/picom/picom.conf &
pgrep -x clipmenud > /dev/null || clipmenud &

######## Wallpaper & Bar ####
xwallpaper --zoom ~/wall/whitewaves.jpg &
polybar main -c ~/.config/polybar/config-git.ini &
